### ISSUE TITLE
API Url required

### ISSUE THREAD

**Issue by Lance-Mao** [imsatoshi/GeneTrader#1]
![image](https://github.com/user-attachments/assets/394c68c1-f19e-4e7f-848c-c7e9a352bf9d)
Can you help see this problem? Thanks

**Comment by imsatoshi** [comment]
You should set apiserver parameter to True.

**Comment by Lance-Mao** [comment]
![image](https://github.com/user-attachments/assets/21812904-2e6c-4f39-a6b2-83bf00f316a2)
![image](https://github.com/user-attachments/assets/2aa93aa7-2041-458f-b201-f9c5a18ecf76)
These are correctly configured

**Comment by imsatoshi** [comment]
Problem solved? @Lance-Mao

**Comment by Lance-Mao** [comment]
solved
