### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by dorimon5** [imsatoshi/GeneTrader#2]
hi! good day! when i'm trying to run this command .  python3.8 main.py --download --start-date 20240901 --end-date 20240922
 
it got this error.

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from genetic_algorithm.operators import crossover, mutate, select_tournament
  File "/home/diamond/repo/GeneTrader/genetic_algorithm/operators.py", line 5, in <module>
    def crossover(parent1: Individual, parent2: Individual) -> tuple[Individual, Individual]:
TypeError: 'type' object is not subscriptable

pls help. thanks!

**Comment by imsatoshi** [comment]
Could you show your config file? The default config file is ga.json.

**Comment by imsatoshi** [comment]
I think the latest commit has already solved your errors.

**Comment by imsatoshi** [comment]
Problem solved.
