### ISSUE TITLE
 No matching distribution found for python>=3.7

### ISSUE THREAD

**Issue by dorimon5** [imsatoshi/GeneTrader#3]
helo! good day! i got this error while trying to install the requirements using this command " pip install -r requirements.txt ".

ERROR: Could not find a version that satisfies the requirement python>=3.7 (from versions: none)
ERROR: No matching distribution found for python>=3.7

Please help. Thank you!

**Comment by imsatoshi** [comment]
Update your python version.

**Comment by dorimon5** [comment]
I already update my python boss. i have python3.8 & python3.12 but still i got the error
