### ISSUE TITLE
How many trades per day

### ISSUE THREAD

**Issue by lackofcodingskillz** [imsatoshi/GeneTrader#4]
Hi I just ran a back test of the program and it gave me back some ridiculous profit percentage 2million % to be exact (GeneTrader_gen5_1726907875_9248), I just want to know if you use this strategy for dry live? If so how many trades do you get per day usually and how much profit do you get per month?

**Comment by imsatoshi** [comment]
I believe the average number of trades per day should be reduced, ideally to less than one. The win rate is a key metric for me, and I understand there is a trade-off between the number of trades and the win rate. You can design the fitness function as you see fit, with the final optimization goal focused on maximizing profit. The trading strategy is dynamic, and I will run it through both dry-run and live tests.

**Comment by lackofcodingskillz** [comment]
![Screenshot 2024-09-29 at 22 00 04](https://github.com/user-attachments/assets/306a50e8-17d3-42b1-a037-48c6984ac5fd)

This is what I get for this month's backtest. As you can see it says there're over 400, that means on average there're 13 trades per day, but I'm not seeing any trade. Also I don't think this number is realistic (Even before I run hyperopt it was giving like 1000% per month)

**Comment by imsatoshi** [comment]
Which strategy do you use? I prefer strategies with lower trade frequency. Additionally, the dry-run results should align closely with the back-testing results. Finally, the strategy should be optimized using a GA (Genetic Algorithm).

**Comment by lackofcodingskillz** [comment]
GeneTrader_gen5_1726907875_9248

**Comment by imsatoshi** [comment]
It's over-fitted.  Ignore it. You can try any strategy you like.
