### ISSUE TITLE
bark endpoint

### ISSUE THREAD

**Issue by fvlasie** [imsatoshi/GeneTrader#7]
Hello! Is it possible to run GeneTrader without bark endpoint?

**Comment by imsatoshi** [comment]
Sure. Will fix it later.

**Comment by fvlasie** [comment]
I am getting this error when trying to run ` python3 main.py --download `
```
admin@iMac-Pro GeneTrader % python3 main.py --download
Traceback (most recent call last):
  File "/Users/admin/Documents/Kraken/GeneTrader/main.py", line 10, in <module>
    from config.settings import Settings
  File "/Users/admin/Documents/Kraken/GeneTrader/config/settings.py", line 50, in <module>
    settings = Settings()
  File "/Users/admin/Documents/Kraken/GeneTrader/config/settings.py", line 36, in __init__
    self.bark_key = self.config["bark_key"]
                    ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'bark_key'

```

**Comment by imsatoshi** [comment]
> Thank you for the update! I am getting this error when trying to run `python3 main.py --download`
> 
> ```
> admin@iMac-Pro GeneTrader % python3 main.py --download
> Traceback (most recent call last):
>   File "/Users/admin/Documents/Kraken/GeneTrader/main.py", line 10, in <module>
>     from config.settings import Settings
>   File "/Users/admin/Documents/Kraken/GeneTrader/config/settings.py", line 50, in <module>
>     settings = Settings()
>   File "/Users/admin/Documents/Kraken/GeneTrader/config/settings.py", line 36, in __init__
>     self.bark_key = self.config["bark_key"]
>                     ~~~~~~~~~~~^^^^^^^^^^^^
> KeyError: 'bark_key'
> ```

Check out the ga.json.example.
